package pe.edu.upeu.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val AndinaLightColors = lightColorScheme(
    primary = Color(0xFF006B5B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF82F8DD),
    onPrimaryContainer = Color(0xFF00201A),
    secondary = Color(0xFF4C635C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCFE9DE),
    onSecondaryContainer = Color(0xFF08201A),
    tertiary = Color(0xFF416277),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC5E7FF),
    onTertiaryContainer = Color(0xFF001E2D),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFAFDF9),
    onBackground = Color(0xFF191C1A),
    surface = Color(0xFFFAFDF9),
    onSurface = Color(0xFF191C1A),
    surfaceVariant = Color(0xFFDBE5DF),
    onSurfaceVariant = Color(0xFF404944),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F7F3),
    surfaceContainer = Color(0xFFEEF1ED),
    surfaceContainerHigh = Color(0xFFE8ECE8),
    surfaceContainerHighest = Color(0xFFE3E6E2),
    outline = Color(0xFF707974),
    outlineVariant = Color(0xFFBFC9C3),
    inverseSurface = Color(0xFF2E312F),
    inverseOnSurface = Color(0xFFF0F1EE),
    inversePrimary = Color(0xFF65DBC1)
)

val AndinaDarkColors = darkColorScheme(
    primary = Color(0xFF65DBC1),
    onPrimary = Color(0xFF00382F),
    primaryContainer = Color(0xFF005143),
    onPrimaryContainer = Color(0xFF82F8DD),
    secondary = Color(0xFFB3CCC2),
    onSecondary = Color(0xFF1F352F),
    secondaryContainer = Color(0xFF354C45),
    onSecondaryContainer = Color(0xFFCFE9DE),
    tertiary = Color(0xFFA9CBE3),
    onTertiary = Color(0xFF0E3448),
    tertiaryContainer = Color(0xFF294B5F),
    onTertiaryContainer = Color(0xFFC5E7FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF111412),
    onBackground = Color(0xFFE1E3DF),
    surface = Color(0xFF111412),
    onSurface = Color(0xFFE1E3DF),
    surfaceVariant = Color(0xFF404944),
    onSurfaceVariant = Color(0xFFBFC9C3),
    surfaceContainerLowest = Color(0xFF0C0F0D),
    surfaceContainerLow = Color(0xFF191C1A),
    surfaceContainer = Color(0xFF1D201E),
    surfaceContainerHigh = Color(0xFF282B28),
    surfaceContainerHighest = Color(0xFF333633),
    outline = Color(0xFF89938D),
    outlineVariant = Color(0xFF404944),
    inverseSurface = Color(0xFFE1E3DF),
    inverseOnSurface = Color(0xFF2E312F),
    inversePrimary = Color(0xFF006B5B)
)
